### ISSUE TITLE
Ring placements in v1 of the Radar

### ISSUE THREAD

**Issue by nasthagiri** [openedx/openedx-tech-radar#4]
Thank you for bringing this over the line. Unlike Thoughtworks' Tech Radar that denotes *movement* of industry adoptions and trends, the Open edX Tech Radar is intended to be an evolving source of truth of community-wide technical decisions. Other organizations have also adopted this technique and I hope it will serve its long-term purpose for this community.

I have reviewed the position of the blips. Here is input for consideration:

**Techniques**

1. **BEES** > Adopted -> Accepted: This architecture strategy was published a few months ago in the summer. I imagine there's more to do for it to be widely known and adopted in the vernacular, including ADRs, communications, etc.

2. **Conventional Commits** > Adopted -> Accepted: Last I had checked, CCs were not yet fully adopted. There was an impending effort to add a linter to ensure you're at 100% usage. If you have done so, then yeah, keep it in adopted state. If you haven't, I'd move it to Accepted with the goal of it becoming Adopted soon.

3. **Micro-services** > Clarify: Add a cross-reference to the `Boundaries (DDD)` blip to ensure people don't revert to creating too-small micro-services that are entity-based, exacerbating the current "distributed monolith" situation (where services are incorrectly dependent on each other). Consider rephrasing *"small services"* to *"business and organization aligned smaller services"*.

4. **Synchronous signal handling (Django signals)** > Adopted -> Accepted: Correct me if I'm wrong - the use of Django signals is still rudimentary in our adoption. More needs to be done in providing guidelines and possibly a framework for wider use and adoption. The upcoming Django-Events capability (from EduNext's Django Hooks efforts) will help establish this design pattern with structured APIs, versioning-strategy, etc.

5. **Standards-based Development** > Provisional -> Accepted/Adopted: I am curious why this was put under Provisional. There are more than 3 example standards listed in the description that have already been implemented and widely adopted on the platform.

6. **Test-driven Development** > Provisional -> ??: Are there any teams that are actually able to use TDD in their regular development? Perhaps they are able to in MFEs? The local test cycle in the Django apps today typically don't allow for TDD.

7. **Server side Templates** > Clarify: Would you still want to use server-side templates for certain frontends? For example, Django admin pages? Legacy web-response pages? If so, may want to clarify the text to allow for server-side templates for certain frontends that are not worthwhile to support in MFEs.

**Open edX**

8. **celery-utils** > Provisional -> Accepted: celery-utils has been around for several years now and used in multiple repositories. The implementation has been pretty stable for the last few years.

**Technologies**

9. **attrs** > Adopted -> Accepted: Has there been much discussion about the learnings and tradeoffs with using attrs? My sense was that it's been starting to get traction, but not fully adopted yet with understanding on when to use and when not to.

**Comment by sarina** [comment]
> Regarding TDD, would we lose anything by dropping it from the radar?

I don't think so, frankly.

@davidjoy if you can weigh in with your thoughts, I can go ahead and make these changes to the radar.
