### ISSUE TITLE
Rings should not be determined by filepath

### ISSUE THREAD

**Issue by sarina** [openedx/openedx-tech-radar#6]
Right now, the Radar's import & export scripts use filepath, eg `radars/primary/quadrants/technologies/rings/adopted/blips/django.json`, to read what ring a blip is part of (see https://github.com/openedx/openedx-tech-radar/blob/main/scripts/export.js#L63-L65).

Rewrite these import/export scripts, and adjust all the filepaths, to not rely on filepath for ring definition. Why? Having the ring in the filepath means that for any needed change to a ring, a file must be moved. This destroys history and makes `git blame` worthless. It is also duplicative work, as the ring position is also defined in the json.

Suggestion: I suggest the filepaths should be, eg, `radars/primary/quadrants/technologies/blips/django.json`. That is, the _quadrant_ remains defined in the filepath. Why? We don't expect a blip's quadrant to change, and this makes the ~100+ blip definitions a little more easy to find, as they're sorted by quadrant.

**Comment by Carlos-Muniz** [comment]
It makes sense to reorganize the blips by just quadrant, if the blip will be changing between rings as the technology is upgraded. However, why doe we need quadrants at all if each blip json also contains the information for the quadrant and ring?
